import fs from 'fs';
import express from 'express';
import cors from 'cors';
import { createServer } from 'http';
import { Server } from 'socket.io';
import path from 'path';
import { fileURLToPath } from 'url';
import crypto from 'crypto';
import multer from 'multer';
import config from './src/config.js';
import orchestrator from './src/orchestrator.js';
import healthChecker from './src/healthChecker.js';
import providerManager from './src/providerManager.js';
import statusPersistence from './src/statusPersistence.js';
import pricingManager from './src/pricingManager.js';
import { countTokens } from './src/utils/tokenCounter.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const sessions = new Map();

const app = express();
const httpServer = createServer(app);

// Serve SPA
app.use(express.static(path.join(__dirname, 'client/dist')));
console.log(`Serving SPA from: ${path.join(__dirname, 'client/dist')}`);

// API routes are defined below...

// CORS configuration - currently permissive for development
// TODO: In production, restrict to specific allowed origins
const io = new Server(httpServer, {
    cors: {
        origin: process.env.ALLOWED_ORIGINS ? process.env.ALLOWED_ORIGINS.split(',') : "*",
        methods: ["GET", "POST"]
    }
});

app.use(cors());
app.use(express.json({ limit: '1mb' })); // Add request size limit

// Multer config for audio file uploads (speech-to-text)
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 100 * 1024 * 1024 } // 100MB max (Groq dev tier limit)
});

// Helper to log to console and socket
const log = (msg) => {
    console.log(msg);
    io.emit('log', msg);
};

// Middleware for parameter validation
const validateGenerateParams = (req, res, next) => {
    const { prompt, systemPrompt } = req.body;

    if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
        return res.status(400).json({ error: 'Missing or invalid "prompt" parameter' });
    }

    const promptTokens = countTokens(prompt);
    if (promptTokens > config.maxPromptTokens) {
        return res.status(400).json({
            error: `Prompt too long (${promptTokens} tokens, max ${config.maxPromptTokens})`
        });
    }

    if (systemPrompt && typeof systemPrompt === 'string') {
        const systemTokens = countTokens(systemPrompt);
        if (systemTokens > config.maxSystemTokens) {
            return res.status(400).json({
                error: `System prompt too long (${systemTokens} tokens, max ${config.maxSystemTokens})`
            });
        }
    }

    next();
};

// API Endpoints
app.post('/api/login', (req, res) => {
    const { username, password } = req.body;
    if (username === config.admin.username && password === config.admin.password) {
        const token = crypto.randomUUID();
        sessions.set(token, Date.now());
        res.json({ success: true, token });
    } else {
        res.status(401).json({ error: 'Invalid credentials' });
    }
});

const requireAuth = (req, res, next) => {
    const auth = req.headers.authorization;
    if (!auth || !auth.startsWith('Bearer ') || !sessions.has(auth.slice(7))) {
        return res.status(401).json({ error: 'Unauthorized' });
    }
    next();
};

app.post('/api/ai/image', validateGenerateParams, async (req, res) => {
    try {
        const result = await orchestrator.generateImage(req.body);
        res.json(result);
        log(`Image generated by ${result.provider}`);
        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } catch (error) {
        log(`Image generation failed: ${error.message}`);
        res.status(500).json({ error: error.message });
    }
});

// Simple GET route for images
app.get('/image', async (req, res) => {
    const { prompt, model } = req.query;
    if (!prompt) {
        return res.status(400).send('Missing prompt query parameter');
    }
    try {
        const result = await orchestrator.generateImage({ prompt, model });
        if (result.imageUrl.startsWith('data:')) {
            // It's a base64 image from Cloudflare
            const base64Data = result.imageUrl.split(',')[1];
            const img = Buffer.from(base64Data, 'base64');
            res.writeHead(200, {
                'Content-Type': 'image/png',
                'Content-Length': img.length
            });
            res.end(img);
        } else {
            // It's a URL from Pollinations
            res.redirect(result.imageUrl);
        }
        log(`Image served by ${result.provider} via GET /image`);
    } catch (error) {
        res.status(500).send(error.message);
    }
});

app.post('/api/ai', validateGenerateParams, async (req, res) => {
    try {
        const result = await orchestrator.generate(req.body);
        res.json(result);
        log(`Request served by ${result.provider}`);
        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } catch (error) {
        log(`Request failed: ${error.message}`);
        res.status(500).json({ error: error.message });
    }
});

// Speech-to-text (audio transcription via Groq Whisper)
app.post('/api/ai/transcribe', upload.single('file'), async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: 'Missing audio file (field "file")' });
        }

        const { model, language } = req.body;
        const result = await orchestrator.transcribe({
            audio: req.file.buffer,
            filename: req.file.originalname,
            mimetype: req.file.mimetype,
            model: model || undefined,
            language: language || undefined
        });

        res.json(result);
        log(`Audio transcribed by ${result.provider} (${result.model})`);
        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } catch (error) {
        log(`Transcription failed: ${error.message}`);
        const status = /rate limit|429/i.test(error.message) ? 429 : (/too large/i.test(error.message) ? 413 : 500);
        res.status(status).json({ error: error.message });
    }
});

// Multer error handler (file too large, unexpected field, etc.)
app.use((err, req, res, next) => {
    if (err instanceof multer.MulterError) {
        if (err.code === 'LIMIT_FILE_SIZE') {
            return res.status(413).json({ error: 'Audio file too large (max 100MB)' });
        }
        return res.status(400).json({ error: `Upload error: ${err.message}` });
    }
    next(err);
});

// Streaming endpoint (SSE-like over POST chunked response)
app.post('/api/ai/stream', validateGenerateParams, async (req, res) => {
    try {
        const params = req.body || {};

        // Set SSE headers
        res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            Connection: 'keep-alive'
        });
        res.flushHeaders && res.flushHeaders();

        const sendEvent = (event, data) => {
            try {
                res.write(`event: ${event}\n`);
                res.write(`data: ${JSON.stringify(data)}\n\n`);
            } catch (e) {
                console.error('Failed to send SSE event', e.message);
            }
        };

        // Use orchestrator.stream which will call onData with {type, token/content}
        await orchestrator.stream(params, (payload) => {
            if (!payload || !payload.type) return;
            if (payload.type === 'start') {
                sendEvent('start', { provider: payload.provider, model: payload.model });
            } else if (payload.type === 'data') {
                sendEvent('data', { token: payload.token });
            } else if (payload.type === 'end') {
                sendEvent('end', { 
                    content: payload.content, 
                    responseTime: payload.responseTime, 
                    tokens: payload.tokens,
                    inputTokens: payload.inputTokens,
                    outputTokens: payload.outputTokens
                });
            }
        });

        // Close stream
        res.write('event: done\n');
        res.write('data: {}\n\n');
        res.end();

        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } catch (error) {
        console.error('Streaming request failed:', error.message || error);
        try {
            res.write('event: error\n');
            res.write(`data: ${JSON.stringify({ error: error.message || String(error) })}\n\n`);
            res.end();
        } catch (e) { /* ignore */ }
    }
});

app.get('/api/status', async (req, res) => {
    const nextModel = await orchestrator.findNextCandidate();
    res.json({
        providers: providerManager.getAllProviders(),
        usage: providerManager.usage,
        nextModel: nextModel || null
    });
});

app.get('/api/usage/stats', (req, res) => {
    const stats = statusPersistence.getStats();
    res.json({
        ...stats,
        providerLimits: Object.keys(config.providers).reduce((acc, key) => {
            acc[key] = {
                daily_limit: config.providers[key].daily_limit,
                daily_token_limit: config.providers[key].daily_token_limit
            };
            return acc;
        }, {})
    });
});

app.get('/api/usage/stats/:timeframe', (req, res) => {
    const { timeframe } = req.params;
    res.json(statusPersistence.getStatsByTimeframe(timeframe));
});

app.get('/api/usage/history', (req, res) => {
    const limit = parseInt(req.query.limit) || 100;
    const offset = parseInt(req.query.offset) || 0;
    const filters = {
        providerId: req.query.providerId,
        modelName: req.query.modelName,
        status: req.query.status,
        sortBy: req.query.sortBy,
        sortOrder: req.query.sortOrder
    };
    res.json(statusPersistence.getHistory(limit, offset, filters));
});

app.get('/api/usage/timeseries', (req, res) => {
    const { interval, metric, providerId, modelName } = req.query;
    const data = statusPersistence.getTimeSeriesStats(interval, metric, { providerId, modelName });
    res.json(data);
});

app.get('/api/usage/pricing', (req, res) => {
    res.json(statusPersistence.getAllPricing());
});

app.get('/health', (req, res) => {
    res.json({ status: 'ok', uptime: process.uptime() });
});

app.get('/api/settings', requireAuth, async (req, res) => {
    try {
        const envPath = path.join(__dirname, '.env');
        
        await fs.promises.access(envPath);
        const envContent = await fs.promises.readFile(envPath, 'utf8');
        
        const settings = {};
        const lines = envContent.split('\n');
        
        lines.forEach(line => {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('#')) {
                const [key, ...valueParts] = trimmed.split('=');
                if (key && valueParts.length > 0) {
                    settings[key] = valueParts.join('=');
                }
            }
        });
        
        res.json(settings);
    } catch (error) {
        console.error('GET /api/settings Error:', error);
        res.status(500).json({
            error: 'Failed to read settings file',
            message: error.message
        });
    }
});

const PROVIDER_TESTS = {
    GEMINI_API_KEY: {
        url: (v) => `https://generativelanguage.googleapis.com/v1beta/models?key=${v}`,
        headers: () => ({})
    },
    GROQ_API_KEY: {
        url: () => 'https://api.groq.com/openai/v1/models',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    },
    CEREBRAS_API_KEY: {
        url: () => 'https://api.cerebras.ai/v1/models',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    },
    HF_API_KEY: {
        url: () => 'https://huggingface.co/api/models?search=test&limit=1',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    },
    OPENROUTER_API_KEY: {
        url: () => 'https://openrouter.ai/api/v1/models',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    },
    MISTRAL_API_KEY: {
        url: () => 'https://api.mistral.ai/v1/models',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    },
    COHERE_API_KEY: {
        url: () => 'https://api.cohere.com/v1/models',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    },
    NOVITA_API_KEY: {
        url: () => 'https://api.novita.ai/v3/openai/models',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    },
    GITHUB_TOKEN: {
        url: () => 'https://api.github.com/user',
        headers: (v) => ({ 'Authorization': `Bearer ${v}` })
    }
};

app.post('/api/settings/test/:key', requireAuth, async (req, res) => {
    const { key } = req.params;
    const value = req.body.value;
    const originalValue = process.env[key];
    
    try {
        if (!value) {
            return res.status(400).json({ error: 'Missing value' });
        }
        
        process.env[key] = value;
        
        if (key === 'CLOUDFLARE_TOKEN' && process.env.CLOUDFLARE_ACCOUNT_ID) {
            const testUrl = `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/ai/run/@cf/meta/llama-4-scout-17b-16e-instruct`;
            const response = await fetch(testUrl, {
                headers: { 'Authorization': `Bearer ${value}` }
            });
            if (!response.ok) {
                throw new Error(`Cloudflare API test failed: ${response.status} ${response.statusText}`);
            }
            const data = await response.json();
            if (!data.result) {
                throw new Error('Cloudflare API test failed: No result data');
            }
            res.json({ success: true, message: 'Cloudflare API key test successful', data });
        } else if (PROVIDER_TESTS[key]) {
            const { url, headers } = PROVIDER_TESTS[key];
            const response = await fetch(url(value), { headers: headers(value) });
            if (!response.ok) {
                throw new Error(`API test failed: ${response.status} ${response.statusText}`);
            }
            const data = await response.json();
            res.json({ success: true, message: 'API key test successful', data });
        } else {
            res.json({ success: true, message: 'Value updated' });
        }
    } catch (error) {
        console.error(`Test failed for ${key}: ${error.message}`);
        res.status(400).json({ success: false, error: error.message });
    } finally {
        if (originalValue !== undefined) {
            process.env[key] = originalValue;
        }
    }
});

app.post('/api/settings', requireAuth, async (req, res) => {
    try {
        const envPath = path.join(__dirname, '.env');
        
        await fs.promises.access(envPath);
        let envContent = await fs.promises.readFile(envPath, 'utf8');
        
        Object.keys(req.body).forEach(key => {
            const newValue = req.body[key];
            const regex = new RegExp(`^${key}=.*$`, 'm');
            if (regex.test(envContent)) {
                envContent = envContent.replace(regex, `${key}=${newValue}`);
            }
        });
        
        await fs.promises.writeFile(envPath, envContent, 'utf8');
        log('Settings updated successfully');
        res.json({ success: true, message: 'Settings updated successfully' });
    } catch (error) {
        log(`Failed to update settings: ${error.message}`);
        res.status(500).json({ success: false, error: error.message });
    }
});

app.post('/api/status/check', async (req, res) => {
    log('Manual status check triggered via API');
    try {
        await healthChecker.checkAll(true);
        res.json({ status: 'completed', message: 'Health check completed successfully' });
    } catch (error) {
        log(`Manual check failed: ${error.message}`);
        res.status(500).json({
            status: 'failed',
            error: error.message
        });
    }
});

// OpenAI-compatible /v1/chat/completions endpoint
function openaiMessagesToInternal(messages) {
    let systemPrompt = '';
    const history = [];
    let prompt = '';

    for (let i = 0; i < messages.length; i++) {
        const msg = messages[i];
        if (msg.role === 'system') {
            systemPrompt = (systemPrompt ? systemPrompt + '\n' : '') + msg.content;
        } else if (i === messages.length - 1 && msg.role === 'user') {
            prompt = msg.content;
        } else {
            history.push({ role: msg.role === 'assistant' ? 'ai' : 'user', content: msg.content });
        }
    }

    return { systemPrompt, history, prompt };
}

app.post('/v1/chat/completions', async (req, res) => {
    const { messages, temperature, max_tokens, stream: doStream, response_format } = req.body;

    if (!Array.isArray(messages) || messages.length === 0) {
        return res.status(400).json({
            error: { message: 'messages is required and must be a non-empty array', type: 'invalid_request_error', param: 'messages', code: null }
        });
    }

    for (const msg of messages) {
        if (!msg.role || typeof msg.role !== 'string' || !msg.content || typeof msg.content !== 'string') {
            return res.status(400).json({
                error: { message: 'Each message must have a valid role and content string', type: 'invalid_request_error', param: 'messages', code: null }
            });
        }
    }

    const { systemPrompt, history, prompt } = openaiMessagesToInternal(messages);
    const params = { prompt, messages: history, systemPrompt, temperature, max_tokens };
    if (response_format && response_format.type) {
        params.response_format = response_format;
    }

    if (doStream) {
        const id = 'chatcmpl-' + Date.now() + Math.random().toString(36).slice(2, 8);
        res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive'
        });
        res.flushHeaders && res.flushHeaders();

        let modelName = 'unknown';

        try {
            await orchestrator.stream(params, (payload) => {
                if (payload.type === 'start') {
                    modelName = payload.model;
                    const chunk = {
                        id, object: 'chat.completion.chunk',
                        created: Math.floor(Date.now() / 1000),
                        model: modelName,
                        choices: [{ index: 0, delta: { role: 'assistant', content: '' }, finish_reason: null }]
                    };
                    res.write(`data: ${JSON.stringify(chunk)}\n\n`);
                } else if (payload.type === 'data') {
                    const chunk = {
                        id, object: 'chat.completion.chunk',
                        created: Math.floor(Date.now() / 1000),
                        model: modelName,
                        choices: [{ index: 0, delta: { content: payload.token }, finish_reason: null }]
                    };
                    res.write(`data: ${JSON.stringify(chunk)}\n\n`);
                } else if (payload.type === 'end') {
                    const chunk = {
                        id, object: 'chat.completion.chunk',
                        created: Math.floor(Date.now() / 1000),
                        model: modelName,
                        choices: [{ index: 0, delta: {}, finish_reason: 'stop' }]
                    };
                    res.write(`data: ${JSON.stringify(chunk)}\n\n`);
                    res.write('data: [DONE]\n\n');
                    res.end();
                }
            });
        } catch (error) {
            try {
                const errChunk = {
                    id, object: 'chat.completion.chunk',
                    created: Math.floor(Date.now() / 1000),
                    model: modelName,
                    choices: [{ index: 0, delta: {}, finish_reason: 'stop' }]
                };
                res.write(`data: ${JSON.stringify(errChunk)}\n\n`);
                res.write('data: [DONE]\n\n');
                res.end();
            } catch (e) { /* ignore */ }
        }

        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } else {
        try {
            const result = await orchestrator.generate(params);
            const id = 'chatcmpl-' + Date.now() + Math.random().toString(36).slice(2, 8);
            res.json({
                id,
                object: 'chat.completion',
                created: Math.floor(Date.now() / 1000),
                model: result.model,
                choices: [{ index: 0, message: { role: 'assistant', content: result.content }, finish_reason: 'stop' }],
                usage: {
                    prompt_tokens: result.inputTokens,
                    completion_tokens: result.outputTokens,
                    total_tokens: result.tokens
                }
            });
            log(`OpenAI-compatible request served by ${result.provider}`);
            io.emit('status_update', providerManager.getAllProviders());
            io.emit('usage_update');
        } catch (error) {
            log(`OpenAI-compatible request failed: ${error.message}`);
            res.status(500).json({
                error: { message: error.message, type: 'server_error', param: null, code: null }
            });
        }
    }
});

// Socket.io connection
io.on('connection', (socket) => {
    log(`Client connected: ${socket.id}`);
    socket.emit('status_update', providerManager.getAllProviders());

    socket.on('chat_message', async (data) => {
        // Validate input
        if (!data || typeof data !== 'object') {
            socket.emit('chat_error', { message: 'Invalid data format' });
            return;
        }

        if (!data.prompt || typeof data.prompt !== 'string') {
            socket.emit('chat_error', { message: 'Prompt is required and must be a string' });
            return;
        }

        // Sanitize and limit prompt length
        const prompt = data.prompt.trim().substring(0, 10000);
        const systemPrompt = data.systemPrompt && typeof data.systemPrompt === 'string'
            ? data.systemPrompt.trim().substring(0, 5000)
            : undefined;
        const providerId = data.providerId && typeof data.providerId === 'string'
            ? data.providerId.trim().substring(0, 50)
            : undefined;

        try {
            log(`Chat request from TUI: ${prompt.substring(0, 50)}...`);
            // If specific provider requested
            let result;
            if (providerId) {
                const provider = providerManager.getProvider(providerId);
                if (!provider) {
                    socket.emit('chat_error', { message: 'Provider not found' });
                    return;
                }
                const content = await orchestrator.callProvider(provider, prompt, systemPrompt, 0.7);
                result = { provider: provider.name, content };
                providerManager.incrementUsage(provider.id);
            } else {
                result = await orchestrator.generate({
                    prompt,
                    systemPrompt
                });
            }
            socket.emit('chat_response', result);
            io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
        } catch (error) {
            log(`Chat error: ${error.message}`);
            socket.emit('chat_error', { message: error.message });
        }
    });

    socket.on('disconnect', () => {
        log(`Client disconnected: ${socket.id}`);
    });
});

// Serve SPA - catch-all route (must be after all API routes)
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'client/dist', 'index.html'));
});

// Start Server
const PORT = config.port;
httpServer.listen(PORT, async () => {
    log(`Server started on port ${PORT}`);

    // Start Health Checker
    healthChecker.start();

    // Start Pricing Manager
    pricingManager.start();

    // Periodically emit status
    setInterval(() => {
        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    }, 5000);
});

// Handle errors
process.on('uncaughtException', (err) => {
    log(`Uncaught Exception: ${err.message}`);
});

process.on('unhandledRejection', (reason, promise) => {
    log(`Unhandled Rejection: ${reason}`);
});
