import express from 'express';
import cors from 'cors';
import { createServer } from 'http';
import { Server } from 'socket.io';
import path from 'path';
import { fileURLToPath } from 'url';
import config from './src/config.js';
import orchestrator from './src/orchestrator.js';
import healthChecker from './src/healthChecker.js';
import providerManager from './src/providerManager.js';
import statusPersistence from './src/statusPersistence.js';
import pricingManager from './src/pricingManager.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const httpServer = createServer(app);

// Serve SPA
app.use(express.static(path.join(__dirname, 'client/dist')));
console.log(`Serving SPA from: ${path.join(__dirname, 'client/dist')}`);

// API routes are defined below...

// CORS configuration - currently permissive for development
// TODO: In production, restrict to specific allowed origins
const io = new Server(httpServer, {
    cors: {
        origin: process.env.ALLOWED_ORIGINS ? process.env.ALLOWED_ORIGINS.split(',') : "*",
        methods: ["GET", "POST"]
    }
});

app.use(cors());
app.use(express.json({ limit: '1mb' })); // Add request size limit

// Helper to log to console and socket
const log = (msg) => {
    console.log(msg);
    io.emit('log', msg);
};

// Middleware for parameter validation
const validateGenerateParams = (req, res, next) => {
    const { prompt } = req.body;
    if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
        return res.status(400).json({ error: 'Missing or invalid "prompt" parameter' });
    }
    next();
};

// API Endpoints
app.post('/api/login', (req, res) => {
    const { username, password } = req.body;
    if (username === config.admin.username && password === config.admin.password) {
        res.json({ success: true });
    } else {
        res.status(401).json({ error: 'Invalid credentials' });
    }
});

app.post('/api/ai/image', validateGenerateParams, async (req, res) => {
    try {
        const result = await orchestrator.generateImage(req.body);
        res.json(result);
        log(`Image generated by ${result.provider}`);
        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } catch (error) {
        log(`Image generation failed: ${error.message}`);
        res.status(500).json({ error: error.message });
    }
});

// Simple GET route for images
app.get('/image', async (req, res) => {
    const { prompt, model } = req.query;
    if (!prompt) {
        return res.status(400).send('Missing prompt query parameter');
    }
    try {
        const result = await orchestrator.generateImage({ prompt, model });
        if (result.imageUrl.startsWith('data:')) {
            // It's a base64 image from Cloudflare
            const base64Data = result.imageUrl.split(',')[1];
            const img = Buffer.from(base64Data, 'base64');
            res.writeHead(200, {
                'Content-Type': 'image/png',
                'Content-Length': img.length
            });
            res.end(img);
        } else {
            // It's a URL from Pollinations
            res.redirect(result.imageUrl);
        }
        log(`Image served by ${result.provider} via GET /image`);
    } catch (error) {
        res.status(500).send(error.message);
    }
});

app.post('/api/ai', validateGenerateParams, async (req, res) => {
    try {
        const result = await orchestrator.generate(req.body);
        res.json(result);
        log(`Request served by ${result.provider}`);
        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } catch (error) {
        log(`Request failed: ${error.message}`);
        res.status(500).json({ error: error.message });
    }
});

// Streaming endpoint (SSE-like over POST chunked response)
app.post('/api/ai/stream', validateGenerateParams, async (req, res) => {
    try {
        const params = req.body || {};

        // Set SSE headers
        res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            Connection: 'keep-alive'
        });
        res.flushHeaders && res.flushHeaders();

        const sendEvent = (event, data) => {
            try {
                res.write(`event: ${event}\n`);
                res.write(`data: ${JSON.stringify(data)}\n\n`);
            } catch (e) {
                console.error('Failed to send SSE event', e.message);
            }
        };

        // Use orchestrator.stream which will call onData with {type, token/content}
        await orchestrator.stream(params, (payload) => {
            if (!payload || !payload.type) return;
            if (payload.type === 'start') {
                sendEvent('start', { provider: payload.provider, model: payload.model });
            } else if (payload.type === 'data') {
                sendEvent('data', { token: payload.token });
            } else if (payload.type === 'end') {
                sendEvent('end', { 
                    content: payload.content, 
                    responseTime: payload.responseTime, 
                    tokens: payload.tokens,
                    inputTokens: payload.inputTokens,
                    outputTokens: payload.outputTokens
                });
            }
        });

        // Close stream
        res.write('event: done\n');
        res.write('data: {}\n\n');
        res.end();

        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    } catch (error) {
        console.error('Streaming request failed:', error.message || error);
        try {
            res.write('event: error\n');
            res.write(`data: ${JSON.stringify({ error: error.message || String(error) })}\n\n`);
            res.end();
        } catch (e) { /* ignore */ }
    }
});

app.get('/api/status', async (req, res) => {
    const nextModel = await orchestrator.findNextCandidate();
    res.json({
        providers: providerManager.getAllProviders(),
        usage: providerManager.usage,
        nextModel: nextModel || null
    });
});

app.get('/api/usage/stats', (req, res) => {
    const stats = statusPersistence.getStats();
    res.json({
        ...stats,
        providerLimits: Object.keys(config.providers).reduce((acc, key) => {
            acc[key] = {
                daily_limit: config.providers[key].daily_limit,
                daily_token_limit: config.providers[key].daily_token_limit
            };
            return acc;
        }, {})
    });
});

app.get('/api/usage/stats/:timeframe', (req, res) => {
    const { timeframe } = req.params;
    res.json(statusPersistence.getStatsByTimeframe(timeframe));
});

app.get('/api/usage/history', (req, res) => {
    const limit = parseInt(req.query.limit) || 100;
    const offset = parseInt(req.query.offset) || 0;
    const filters = {
        providerId: req.query.providerId,
        modelName: req.query.modelName,
        status: req.query.status,
        sortBy: req.query.sortBy,
        sortOrder: req.query.sortOrder
    };
    res.json(statusPersistence.getHistory(limit, offset, filters));
});

app.get('/api/usage/timeseries', (req, res) => {
    const { interval, metric, providerId, modelName } = req.query;
    const data = statusPersistence.getTimeSeriesStats(interval, metric, { providerId, modelName });
    res.json(data);
});

app.get('/api/usage/pricing', (req, res) => {
    res.json(statusPersistence.getAllPricing());
});

app.get('/health', (req, res) => {
    res.json({ status: 'ok', uptime: process.uptime() });
});

app.post('/api/status/check', async (req, res) => {
    log('Manual status check triggered via API');
    try {
        await healthChecker.checkAll(true);
        res.json({ status: 'completed', message: 'Health check completed successfully' });
    } catch (error) {
        log(`Manual check failed: ${error.message}`);
        res.status(500).json({
            status: 'failed',
            error: error.message
        });
    }
});

// Socket.io connection
io.on('connection', (socket) => {
    log(`Client connected: ${socket.id}`);
    socket.emit('status_update', providerManager.getAllProviders());

    socket.on('chat_message', async (data) => {
        // Validate input
        if (!data || typeof data !== 'object') {
            socket.emit('chat_error', { message: 'Invalid data format' });
            return;
        }

        if (!data.prompt || typeof data.prompt !== 'string') {
            socket.emit('chat_error', { message: 'Prompt is required and must be a string' });
            return;
        }

        // Sanitize and limit prompt length
        const prompt = data.prompt.trim().substring(0, 10000);
        const systemPrompt = data.systemPrompt && typeof data.systemPrompt === 'string'
            ? data.systemPrompt.trim().substring(0, 5000)
            : undefined;
        const providerId = data.providerId && typeof data.providerId === 'string'
            ? data.providerId.trim().substring(0, 50)
            : undefined;

        try {
            log(`Chat request from TUI: ${prompt.substring(0, 50)}...`);
            // If specific provider requested
            let result;
            if (providerId) {
                const provider = providerManager.getProvider(providerId);
                if (!provider) {
                    socket.emit('chat_error', { message: 'Provider not found' });
                    return;
                }
                const content = await orchestrator.callProvider(provider, prompt, systemPrompt, 0.7);
                result = { provider: provider.name, content };
                providerManager.incrementUsage(provider.id);
            } else {
                result = await orchestrator.generate({
                    prompt,
                    systemPrompt
                });
            }
            socket.emit('chat_response', result);
            io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
        } catch (error) {
            log(`Chat error: ${error.message}`);
            socket.emit('chat_error', { message: error.message });
        }
    });

    socket.on('disconnect', () => {
        log(`Client disconnected: ${socket.id}`);
    });
});

// Serve SPA - catch-all route (must be after all API routes)
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'client/dist', 'index.html'));
});

// Start Server
const PORT = config.port;
httpServer.listen(PORT, async () => {
    log(`Server started on port ${PORT}`);

    // Start Health Checker
    healthChecker.start();

    // Start Pricing Manager
    pricingManager.start();

    // Periodically emit status
    setInterval(() => {
        io.emit('status_update', providerManager.getAllProviders());
        io.emit('usage_update');
    }, 5000);
});

// Handle errors
process.on('uncaughtException', (err) => {
    log(`Uncaught Exception: ${err.message}`);
});

process.on('unhandledRejection', (reason, promise) => {
    log(`Unhandled Rejection: ${reason}`);
});
